smoother_server:
  ros__parameters:
    use_sim_time: true
    smoother_plugins: ["SimpleSmoother"]
    
    SimpleSmoother:
      plugin: "amr_navigation::SimpleSmoother"
      tolerance: 1.0e-10
      max_its: 1000
      do_refinement: true