twist_mux:
  ros__parameters:
    use_stamped: false
    topics:
      joystick:
        topic   : joy_vel
        timeout : 0.5
        priority: 100
      keyboard: 
        topic   : key_vel
        timeout : 0.5
        priority: 50
      bumper_retreat:
        topic   : bumper_retreat_cmd_vel
        timeout : 2.0
        priority: 200 
      navigation:
        topic   : navigation_cmd_vel
        timeout : 0.5
        priority: 10